services:
  - type: web
    name: whatsapp-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DIALOG_API_KEY
        sync: false
      - key: API_URL
        sync: false 